# Generated by Django 5.0.1 on 2025-05-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_match_map1_team1_score_match_map1_team2_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='hltv_match_id',
            field=models.IntegerField(blank=True, help_text='ID numérico del partido en HLTV.org', null=True),
        ),
    ]
