# Generated by Django 5.2.1 on 2025-05-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_match_hltv_match_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HLTVUpdateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Activar la actualización automática de partidos desde HLTV.org')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Actualización HLTV',
                'verbose_name_plural': 'Configuraciones de Actualización HLTV',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='last_hltv_update',
            field=models.DateTimeField(blank=True, help_text='Última vez que se verificaron los datos con HLTV', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('LIVE', 'En Vivo'), ('FINISHED', 'Finalizado'), ('CANCELED', 'Cancelado')], default='PENDING', help_text='Estado actual del partido', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='hltv_team_id',
            field=models.IntegerField(blank=True, help_text='ID único del equipo en HLTV.org, si está disponible.', null=True, unique=True),
        ),
    ]
