# Generated by Django 5.2.1 on 2025-05-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_hltvupdatesettings_match_last_hltv_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hltvupdatesettings',
            name='use_real_api',
            field=models.BooleanField(default=False, help_text='Utilizar la API real de HLTV en lugar de datos simulados. Requiere que la librería HLTV esté instalada y configurada.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Marca si este es el torneo activo principal que se muestra en Home.'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='swiss_rules_type',
            field=models.CharField(choices=[('BUCHHOLZ', 'Buchholz System'), ('ESL', 'ESL System')], default='BUCHHOLZ', help_text='Sistema de reglas para emparejamientos en fases suizas', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('MAJOR', 'Major'), ('PGL', 'PGL Tournament'), ('ESL', 'ESL Tournament')], default='MAJOR', help_text='Tipo de torneo (e.g., Major, PGL, ESL)', max_length=10),
        ),
    ]
