# Generated by Django 5.2.1 on 2025-05-14 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_hltvupdatesettings_use_real_api_tournament_is_live_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='fantasy_status',
            field=models.CharField(choices=[('OPEN', 'Open for Picks'), ('LOCKED', 'Picks Locked'), ('FINALIZED', 'Points Calculated')], default='OPEN', help_text='Estado de la fase para las elecciones del Fantasy.', max_length=10),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('twitch_username', models.CharField(blank=True, max_length=100, null=True)),
                ('twitch_profile_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('total_fantasy_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FantasyPlayoffPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False, help_text='Indica si las elecciones para playoffs están cerradas.')),
                ('is_finalized', models.BooleanField(default=False, help_text='Indica si los puntos para playoffs ya han sido calculados.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_as_final_winner', to='tournaments.team')),
                ('quarter_final_winners', models.ManyToManyField(blank=True, related_name='picked_as_qf_winner', to='tournaments.team')),
                ('semi_final_winners', models.ManyToManyField(blank=True, related_name='picked_as_sf_winner', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_playoff_picks', to='tournaments.tournament')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playoff_picks', to='tournaments.userprofile')),
            ],
            options={
                'ordering': ['tournament__name', 'user_profile__user__username'],
                'unique_together': {('user_profile', 'tournament')},
            },
        ),
        migrations.CreateModel(
            name='FantasyPhasePick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False, help_text='Indica si las elecciones para esta fase están cerradas.')),
                ('is_finalized', models.BooleanField(default=False, help_text='Indica si los puntos para esta fase ya han sido calculados.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_picks', to='tournaments.stage')),
                ('teams_0_3', models.ManyToManyField(blank=True, related_name='picked_as_0_3', to='tournaments.team')),
                ('teams_3_0', models.ManyToManyField(blank=True, related_name='picked_as_3_0', to='tournaments.team')),
                ('teams_advance', models.ManyToManyField(blank=True, related_name='picked_to_advance', to='tournaments.team')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_picks', to='tournaments.userprofile')),
            ],
            options={
                'ordering': ['stage__order', 'user_profile__user__username'],
                'unique_together': {('user_profile', 'stage')},
            },
        ),
    ]
