# Generated by Django 5.2.1 on 2025-05-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_stage_fantasy_status_userprofile_fantasyplayoffpick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyphasepick',
            name='team_points_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text="Puntos otorgados por cada equipo en este pick. Ej: {'team_123': 15, 'team_456': 5}"),
        ),
        migrations.AddField(
            model_name='fantasyplayoffpick',
            name='team_points_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text="Puntos otorgados por cada equipo en este pick de playoffs. Ej: {'team_123': 20}"),
        ),
    ]
